package com.juridiqsystem.crm.infra.security.logging;

public enum SecurityEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET_SUCCESS,
    ACCOUNT_LOCKED,
    ACCESS_DENIED,
    UNAUTHORIZED_ACCESS,
    INVALID_TOKEN,
    EXPIRED_TOKEN,
    RATE_LIMIT_TRIGGERED,
    SUSPICIOUS_REQUEST,
    ADMIN_ACTION,
    RESOURCE_ACCESS_DENIED,
    ADMIN_ROUTE_DENIED
}
